### ISSUE TITLE
ask questions?

### ISSUE THREAD

**Issue by LightingSophia** [paarnes/GNSS_Multipath_Analysis_Software#4]
could you please tell me how to run this program (I have already installed the requirements.)? thank you!

**Comment by paarnes** [comment]
Hi,

Sure! Unfortunately, I have not had time to create documentation on how to run the program yet. But that will come. I will also do some clean up so it gets easier to start using this software. However, you should be able to run it if you download the whole repository locally to your PC. In the Multipath_analysis folder you will find a file called [Running_multipath_analysis_example.py](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/blob/master/Multipath_analysis/Running_multipath_analysis_example.py). You should be able to run it directly, based on the path to the different test files in TestData folder. If it does not work, try to replace  the path to some of the test files with the path locally on your computer. As for instance:

from GNSS_MultipathAnalysis import GNSS_MultipathAnalysis
rinex_obs_file = r'C:\Users\XXX\TestData\ObservationFiles\OPEC00NOR_S_20220010000_01D_30S_MO_3.04.rnx'
sp3_file = r'C:\Users\XXX\TestData\SP3\test1.eph'
analysisResults = GNSS_MultipathAnalysis(rinex_obs_file,
                                           desiredGNSSsystems=['G'],
                                          sp3NavFilename_1=sp3_file)

Please let me know if you don't get it to work.

Best regards,
Per Helge

**Comment by LightingSophia** [comment]
Thank you for your relpy！ According to your tips, I encountered the following error，I hope you help me solve the problem, my python is worse,thank you sincerely！

`Currently processing all available bands for GPS:   0%|          | (0/3)D:\PythonProject\GNSS_Multipath_Analysis_Software-master\Multipath_analysis\computeDelayStats.py:366: RuntimeWarning: invalid value encountered in cast
  combined_slip_epoch_elevation_angles = current_sat_elevation_angles[combined_slip_epochs, i+1].astype(int)
Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\matplotlib\texmanager.py", line 255, in _run_checked_subprocess
    report = subprocess.check_output(
  File "D:\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/PythonProject/GNSS_Multipath_Analysis_Software-master/Multipath_analysis/test.py", line 6, in <module>
    analysisResults = GNSS_MultipathAnalysis(rinex_obs_file,
  File "D:\PythonProject\GNSS_Multipath_Analysis_Software-master\Multipath_analysis\GNSS_MultipathAnalysis.py", line 573, in GNSS_MultipathAnalysis
    plotResults(current_code_dict['ion_delay_phase1'], current_code_dict['multipath_range1'], \
  File "D:\PythonProject\GNSS_Multipath_Analysis_Software-master\Multipath_analysis\plotResults.py", line 315, in plotResults
    fig5.savefig(graphDir + "/" +  filename2, dpi=300)
  File "D:\Python38\lib\site-packages\matplotlib\figure.py", line 3328, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "D:\Python38\lib\site-packages\matplotlib\backend_bases.py", line 2362, in print_figure
    result = print_method(
  File "D:\Python38\lib\site-packages\matplotlib\backend_bases.py", line 2228, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "D:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "D:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 457, in _print_pil
    FigureCanvasAgg.draw(self)
  File "D:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "D:\Python38\lib\site-packages\matplotlib\artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\Python38\lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "D:\Python38\lib\site-packages\matplotlib\figure.py", line 3125, in draw
    mimage._draw_list_compositing_images(
  File "D:\Python38\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\Python38\lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3030, in draw
    self._update_title_position(renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 2974, in _update_title_position
    ax.yaxis.get_tightbbox(renderer)  # update offsetText
  File "D:\Python38\lib\site-packages\matplotlib\axis.py", line 1320, in get_tightbbox
    self._update_label_position(renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axis.py", line 2569, in _update_label_position
    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axis.py", line 2104, in _get_tick_boxes_siblings
    tlb, tlb2 = axis._get_ticklabel_bboxes(ticks_to_draw, renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axis.py", line 1299, in _get_ticklabel_bboxes
    return ([tick.label1.get_window_extent(renderer)
  File "D:\Python38\lib\site-packages\matplotlib\axis.py", line 1299, in <listcomp>
    return ([tick.label1.get_window_extent(renderer)
  File "D:\Python38\lib\site-packages\matplotlib\text.py", line 959, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "D:\Python38\lib\site-packages\matplotlib\text.py", line 378, in _get_layout
    _, lp_h, lp_d = _get_text_metrics_with_cache(
  File "D:\Python38\lib\site-packages\matplotlib\text.py", line 97, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
  File "D:\Python38\lib\site-packages\matplotlib\text.py", line 105, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
  File "D:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 226, in get_text_width_height_descent
    return super().get_text_width_height_descent(s, prop, ismath)
  File "D:\Python38\lib\site-packages\matplotlib\backend_bases.py", line 641, in get_text_width_height_descent
    return self.get_texmanager().get_text_width_height_descent(
  File "D:\Python38\lib\site-packages\matplotlib\texmanager.py", line 368, in get_text_width_height_descent
    dvifile = cls.make_dvi(tex, fontsize)
  File "D:\Python38\lib\site-packages\matplotlib\texmanager.py", line 300, in make_dvi
    cls._run_checked_subprocess(
  File "D:\Python38\lib\site-packages\matplotlib\texmanager.py", line 259, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: Failed to process string with tex because latex could not be found


`

**Comment by phaarnes** [comment]
Thanks for letting me know. Do you run the software on own RINEX data now, or are you testing it in the files in TestData?

It seems to be a problem with the plotting and use of TEX as a interpreter. Do you have LaTex/Tex installed on your computer? Because I am using that in the plots to get prettier text formatting. But if this causes problem for user that don't have LaTex on their computer, I have to consider to not to use it. Please test 
to set **plotEstimates=False** and **plotEstimates=False** in the function arguments. Like this for instance:

analysisResults = GNSS_MultipathAnalysis(rinex_obs_file,
                                                                    desiredGNSSsystems=['G'],
                                                                    sp3NavFilename_1=sp3_file,
                                                                    plotEstimates=False,
                                                                    plot_polarplot=False)

With these parameters, the software will not create any plots. And if it runs with these arguments, the software failed earlier due to lack of LaTex support on your computer. If that's the case, I will provide a new code for you.

**Comment by paarnes** [comment]
Thanks for letting me know. Do you run the software on own RINEX data now, or are you testing it in the files in TestData?

It seems to be a problem with the plotting and use of TEX as a interpreter. Do you have LaTex/Tex installed on your computer? Because I am using that in the plots to get prettier text formatting. But if this causes problem for user that don't have LaTex on their computer, I have to consider to not to use it. Please test
to set plotEstimates=False and plotEstimates=False in the function arguments. Like this for instance:

analysisResults = GNSS_MultipathAnalysis(rinex_obs_file,
desiredGNSSsystems=['G'],
sp3NavFilename_1=sp3_file,
plotEstimates=False,
plot_polarplot=False)

With these parameters, the software will not create any plots. And if it runs with these arguments, the software failed earlier due to lack of LaTex support on your computer. If that's the case, I will provide a new code for you.

**Comment by LightingSophia** [comment]
> 

Thank you again for your guidance，it's ok!

**Comment by paarnes** [comment]
No problem! Are you able to run it without any errors now?
